services:
  app:
    build:
      context: .
      target: develop
    env_file:
      - .env
    image: rpg_sim
    volumes:
      - .:/workdir
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  db:
    image: postgres:17.5
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: rpg_sim
    ports:
      - "5432:5432"
    volumes:
      - rpg_sim_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

      


volumes:
  rpg_sim_data: