services:
  app:
    build:
      context: .
      target: develop
    env_file:
      - .env
    image: rpg_sim
    volumes:
      - .:/workdir
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]