[project]
name='Warhammer_RPG_sim'
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "httpx>=0.28.1",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]

